#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"
mkdir -p log
CMD_PREFIX=""
for name in RSMOL_5_10XPOISSON_PARCAE_MODEL_DIR RSMOL_5_10XPOISSON_PARCAE_TOKENIZER_PATH RSMOL_5_10XPOISSON_PARCAE_DATA_DIR RSMOL_5_10XPOISSON_PARCAE_OUTPUT_DIR RSMOL_5_10XPOISSON_PARCAE_STAGE4_GATE RSMOL_5_10XPOISSON_PARCAE_WORLD_SIZE RSMOL_5_10XPOISSON_PARCAE_MICRO_BATCH_SIZE RSMOL_5_10XPOISSON_PARCAE_GRADIENT_ACCUMULATION_STEPS RSMOL_5_10XPOISSON_PARCAE_SEED RSMOL_5_10XPOISSON_PARCAE_MAX_OPTIMIZER_STEPS RSMOL_5_10XPOISSON_PARCAE_WARMUP_STEPS RSMOL_5_10XPOISSON_PARCAE_SCHEDULER_TOTAL_STEPS RSMOL_5_10XPOISSON_PARCAE_SAVE_EVERY RSMOL_5_10XPOISSON_PARCAE_RESUME_FROM RSMOL_5_10XPOISSON_PARCAE_BACKEND RSMOL_5_10XPOISSON_PARCAE_DRY_RUN; do
  value="${!name:-}"
  if [[ -n "$value" ]]; then printf -v quoted_value '%q' "$value"; CMD_PREFIX+="$name=$quoted_value "; fi
done
QUEUE="${RSMOL_5_10XPOISSON_PARCAE_QUEUE:-pdgpu-3090}"
JOB_NAME="${RSMOL_5_10XPOISSON_PARCAE_JOB_NAME:-stage4-5-10xpoisson-parcae-${QUEUE#pdgpu-}-$(date +%m%d%H%M)}"
vc submit -p "$QUEUE" -i docker.v2.aispeech.com/sjtu/sjtu_wumengyue-mhl:0.0.1 -c 32 -m 256G -g 8 -n 1 -j "$JOB_NAME" -d "$SCRIPT_DIR" JOB=1:1 "$SCRIPT_DIR/log/stage4_5_10xpoisson_parcae.JOB.log" --cmd "${CMD_PREFIX}bash scripts/train_stage4_5_10xpoisson_parcae_ddp.sh"
